workflows:
  ionic-ios-build:
    name: Ionic iOS Build (Codemagic)
    instance_type: mac_mini_m2 # Usando o Mac M2 gratuito
    
    environment:
      # Definimos a versão do Node.js
      vars:
        NODE_VERSION: 20.x
        
    scripts:
      # 1. (NOVA CORREÇÃO) Configura o Node.js usando a ferramenta nativa do Codemagic
      - name: Set up Node.js
        script: |
          # Use o gerenciador nativo do Codemagic para configurar a versão do Node.js
          xcode-version use $NODE_VERSION
          
      # 2. Instalar dependências web e forçar a instalação do CLI
      - name: Install dependencies and build web
        script: |
          npm install
          npm install -g @ionic/cli @capacitor/cli
          npm run build
          
      # 3. Adicionar plataforma iOS e sincronizar
      - name: Add and Sync iOS platform
        script: |
          npx cap add ios
          npx cap sync ios
          
      # 4. Instalar CocoaPods (a dependência nativa)
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          
    # 5. Saída: compactar o projeto Xcode para download
    artifacts:
      - $HOME/clone/ios/App/App.xcodeproj
      - $HOME/clone/ios/**/*.xcworkspace
      - 'build/**'
