workflows:
  ionic-ios-build:
    name: Ionic iOS Build (Codemagic)
    instance_type: mac_mini_m2 # Usando o Mac M2 gratuito
    
    # --- A CORREÇÃO ESTÁ AQUI ---
    # Define a versão do Node.js para TODA a máquina
    # Isso é feito ANTES de qualquer script rodar.
    environment:
      node: 20 # Solicita o Node 20

    scripts:
      # 1. (REMOVIDO) O passo 'Set up Node.js' não é mais necessário.
      
      # 2. (AGORA PASSO 1) Instala dependências e compila
      - name: Install dependencies and build web
        script: |
          echo "Verificando a versão do Node (deve ser 20): $(node --version)"
          npm install
          npm run build
              
      # 3. (AGORA PASSO 2) Cria o projeto iOS e o Podfile
      - name: Add and Sync iOS platform (Creates Podfile)
        script: |
          npm install @capacitor/cli @capacitor/ios # Garante que eles estão instalados
          npx cap add ios
          npx cap sync ios
              
      # 4. (AGORA PASSO 3) Instala os CocoaPods
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App 
          pod install

    # 5. (AGORA PASSO 4) DISPONIBILIZA O ARQUIVO .ZIP PARA DOWNLOAD
    artifacts:
      # Compacta a pasta 'ios' inteira para download
      - ios/
