workflows:
  ionic-ios-build:
    name: Ionic iOS Build (Final Attempt)
    instance_type: mac_mini_m2
    
    # --- MUDANÇA: Usamos a ferramenta 'npm-install' que já configura o Node.js 20.x ---
    # Isso elimina a necessidade do passo 'Set up Node.js' manual.
    
    scripts:
      - name: Install dependencies (Node.js 20.x and NPM)
        script: |
          # 1. Configura a versão do Node.js (necessária para que o npm funcione)
          # Usamos o método mais robusto no Codemagic
          if ! command -v npm &> /dev/null
          then
            echo "Installing Node.js 20..."
            nvm install 20
          fi
          
          # 2. Instala as dependências do seu projeto (package.json)
          npm install
          
          # 3. Instala as ferramentas CLI globais (Ionic e Capacitor)
          npm install -g @ionic/cli
          npm install @capacitor/cli @capacitor/ios

      - name: Run web build (Create 'build' folder)
        script: npm run build
          
      - name: Add iOS Platform
        script: npx cap add ios

      - name: Sync Web App with Native Project
        script: npx cap sync ios
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          
    # Saída: compactar o projeto Xcode para download
    artifacts:
      - $HOME/clone/ios/App/App.xcodeproj
      - $HOME/clone/ios/**/*.xcworkspace
      - 'build/**'
