workflows:
  ionic-ios-build:
    name: Ionic iOS Build (Codemagic)
    # 1. USA A MÁQUINA M2 GRATUITA
    instance_type: mac_mini_m2 
    
    environment:
      # 2. DEFINE A VERSÃO DO NODE.JS
      vars:
        NODE_VERSION: 20.x

    scripts:
      # 3. INSTALA O NODE.JS (O JEITO CERTO DO CODEMAGIC)
      - name: Set up Node.js
        script: |
          # Carrega o 'nvm' (gerenciador de versão do Node)
          . $HOME/.nvm/nvm.sh
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          
      # 4. INSTALA AS DEPENDÊNCIAS E COMPILA A WEB
      - name: Install dependencies and build web
        script: |
          npm install
          npm run build
              
      # 5. CRIA O PROJETO IOS E O PODFILE
      - name: Add and Sync iOS platform (Creates Podfile)
        script: |
          npm install @capacitor/cli @capacitor/ios # Garante que eles estão instalados
          npx cap add ios
          npx cap sync ios
              
      # 6. --- A CORREÇÃO ESTÁ AQUI ---
      - name: Install CocoaPods dependencies
        script: |
          # O Podfile está DENTRO de ios/App
          cd ios/App 
          pod install

    # 7. DISPONIBILIZA O ARQUIVO .ZIP PARA DOWNLOAD
    artifacts:
      # Compacta a pasta 'ios' inteira para download
      - ios/
