name: Ionic iOS Build (v3 - A Versão Correta)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v4
      
      # 2. Configura o Node.js 20
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      # 3. Instala todas as dependências
      - name: Instalar todas as dependências
        run: npm install
          
      # 4. Roda o build web (cria a pasta 'build')
      - name: Rodar Build Web (Criar pasta 'build')
        run: npm run build
      
      # 5. Limpa qualquer pasta 'ios' antiga
      - name: Limpar a plataforma iOS antiga
        run: rm -rf ios
        
      # 6. CRIA o projeto iOS (Este é o passo que cria o Podfile)
      - name: Adicionar Plataforma iOS
        run: npx cap add ios
            
      # 7. SINCRONIZA o app web (copia a pasta 'build' para dentro)
      - name: Sincronizar App Web
        run: npx cap sync ios
              
      # 8. INSTALA os Pods (Agora na pasta correta 'ios/App')
      - name: Instalar CocoaPods
        run: |
          cd ios/App
          pod install

      # 9. SAÍDA: Compacta e sobe o projeto para download
      - name: Fazer Upload do Projeto iOS (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
