name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Install dependencies
        run: npm install
          
      - name: Run build (Web assets)
        run: npm run build
      
      # --- NOVA CORREÇÃO: Forçar a instalação e adicionar a plataforma ---
      - name: Install Capacitor and Add iOS Platform
        run: |
          # 1. Instala o CLI do Capacitor e a plataforma iOS
          npm install @capacitor/cli @capacitor/ios
          
          # 2. Adiciona a plataforma iOS (Esta etapa CRIA o Podfile)
          npx cap add ios
        
      - name: Sync Web App with Native Project
        run: npx cap sync ios
          
      - name: Install CocoaPods dependencies
        run: |
          # 3. Roda o pod install DENTRO da pasta iOS/App
          cd ios/App
          pod install
          
      # 4. Saída: compactar o projeto Xcode para download (Artifacts)
      - name: Compactar o projeto iOS
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
