name: Ionic iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      # Instala todas as dependências (React, Ionic, Capacitor, react-scripts)
      - name: Instalar todas as dependências
        run: npm install
          
      # Roda o build web (cria a pasta 'build')
      - name: Rodar Build Web (Criar pasta 'build')
        run: npm run build
      
      # --- PASSO CRUCIAL: LIMPAR E RE-CRIAR A ESTRUTURA NATIVA ---
      # Remove a pasta 'ios' antiga, para garantir que o Podfile seja gerado.
      - name: Limpar a plataforma iOS antiga
        run: rm -rf ios

      # Adicionar e Sincronizar Plataforma iOS (Cria o Podfile em ios/App/)
      - name: Adicionar e Sincronizar Plataforma iOS
        run: |
          npx cap add ios
          npx cap sync ios
          
      # Instala as dependências nativas (CocoaPods)
      # O 'cd ios/App' está correto para acessar o Podfile
      - name: Instalar CocoaPods
        run: |
          cd ios/App
          pod install

      # --- SAÍDA: Compacta e sobe o projeto para download ---
      - name: Fazer Upload do Projeto iOS (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
