name: Node.js CI

# O 'on:' está correto, pois você está na 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # 1. MUDANÇA IMPORTANTE: Mudando para macOS para o build iOS
    runs-on: macos-latest

    # 2. MUDANÇA: Removemos a "matrix" (não precisamos testar 3 versões)
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        # 3. MUDANÇA: Removemos 'cache: 'npm'' para parar o erro
        
    - name: Install dependencies
      # 4. MUDANÇA: Garantindo que está 'npm install'
      run: npm install
      
    - name: Run build
      run: npm run build --if-present
    
    # 5. MUDANÇA: Desativando 'npm test' por enquanto
    # - run: npm test
