name: Ionic iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      # 1. Instala as dependências web (cria node_modules)
      - name: Instalar dependências e CLI
        run: npm install

      # 2. Roda o build web (cria a pasta 'build')
      - name: Rodar Build Web (Criar pasta 'build')
        run: npm run build
      
      # 3. Limpa e RE-CRIA a estrutura nativa
      - name: Limpar e Adicionar Plataforma iOS
        run: |
          rm -rf ios # Limpa a pasta iOS
          npx cap add ios # Cria a pasta iOS/App e o Podfile
          npx cap sync ios
          
      # 4. INSTALAÇÃO DO COCOAPODS (CORREÇÃO DE PERMISSÃO E CAMINHO)
      - name: Instalar dependências nativas (CocoaPods)
        # Usa 'working-directory' para entrar na pasta correta sem chance de erro
        working-directory: ios/App 
        run: |
          # 4a. Força a atualização do repositório (evita problemas de cache)
          sudo pod repo update 
          # 4b. Roda a instalação
          pod install

      # 5. SAÍDA: Compacta e sobe o projeto para download
      - name: Fazer Upload do Projeto iOS (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
