name: Ionic iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      # 1. Instala as dependências (React, Ionic, Capacitor, react-scripts)
      - name: Instalar todas as dependências
        run: npm install
          
      # 2. Roda o build web (cria a pasta 'build')
      - name: Rodar Build Web (Criar pasta 'build')
        run: npm run build
      
      # 3. Limpar pasta iOS
      - name: Limpar a plataforma iOS antiga
        run: rm -rf ios

      # 4. Adicionar e Sincronizar Plataforma iOS (Cria o Podfile em ios/App/)
      - name: Adicionar e Sincronizar Plataforma iOS
        run: |
          npx cap add ios
          npx cap sync ios
          
      # 5. --- CORREÇÃO FINAL: FORÇAR ATUALIZAÇÃO E INSTALAÇÃO DOS PODS ---
      - name: Instalar CocoaPods e dependências (sudo)
        run: |
          # 5a. Entra na pasta correta
          cd ios/App
          # 5b. Força a atualização do repositório (evita o erro No Podfile's)
          # Isso é frequentemente necessário em máquinas CI/CD novas
          sudo pod repo update 
          # 5c. Roda a instalação
          pod install
          
      # 6. SAÍDA: Compacta e sobe o projeto para download
      - name: Fazer Upload do Projeto iOS (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
