name: Ionic iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      # 1. Instala todas as dependências (React, Ionic, Capacitor, react-scripts)
      - name: Instalar todas as dependências
        run: npm install
          
      # 2. Roda o build web (cria a pasta 'build')
      - name: Rodar Build Web (Criar pasta 'build')
        run: npm run build
      
      # 3. Limpar pasta iOS
      - name: Limpar a plataforma iOS antiga
        run: rm -rf ios
        
      # 4. (NOVO) Instala as ferramentas nativas ANTES
      - name: Instalar CocoaPods
        run: sudo gem install cocoapods

      # 5. Sincroniza o Capacitor (Isso vai rodar 'add ios' e criar o Podfile)
      - name: Sincronizar Capacitor (Cria Podfile)
        run: npx cap sync ios
          
      # 6. Instala as dependências do Podfile
      - name: Instalar Dependências do CocoaPods
        run: |
          cd ios/App
          pod install

      # 7. SAÍDA: Compacta e sobe o projeto para download
      - name: Fazer Upload do Projeto iOS (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: DudyApp-Xcode-Project
          path: ios/
